version: '2.0'

services:
  httpd:
    build: .
    restart: always
    ports:
      - '880:80'
      - '4430:443'
    volumes:
      - ./data:/var/www
      - ./apache-conf:/etc/apache2
      - ./letsencrypt:/etc/letsencrypt
      - ./ssl:/etc/ssl
    networks:
      - 'database'
      - 'web'

networks:
  database:
    external: true
  web:
    external: true

